import { PrismaClient } from '@prisma/client';
import { blockDates, releaseDates } from '../services/inventarioService.js';

const p = new PrismaClient();

async function main() {
  // Check before
  const before = await p.inventario.findMany({
    where: { habitacion: 'Pewmafe', fecha: { gte: new Date('2026-10-01'), lt: new Date('2026-10-05') } },
    orderBy: { fecha: 'asc' },
  });
  console.log('BEFORE blockDates:');
  for (const e of before) console.log(`  ${e.fecha.toISOString()} disponible=${e.disponible}`);

  // Block
  console.log('\nCalling blockDates("Pewmafe", 2026-10-01, 2026-10-05)...');
  await blockDates('Pewmafe', new Date('2026-10-01'), new Date('2026-10-05'));

  // Check after
  const after = await p.inventario.findMany({
    where: { habitacion: 'Pewmafe', fecha: { gte: new Date('2026-10-01'), lt: new Date('2026-10-05') } },
    orderBy: { fecha: 'asc' },
  });
  console.log('\nAFTER blockDates:');
  for (const e of after) console.log(`  ${e.fecha.toISOString()} disponible=${e.disponible}`);

  // Now let's see what dates blockDates generates internally
  const dates: Date[] = [];
  const current = new Date('2026-10-01');
  const end = new Date('2026-10-05');
  while (current < end) {
    dates.push(new Date(current));
    current.setDate(current.getDate() + 1);
  }
  console.log('\nDates generated by blockDates:');
  for (const d of dates) console.log(`  ${d.toISOString()}`);

  // Check exact match
  console.log('\nDirect query with IN dates:');
  const result = await p.inventario.updateMany({
    where: { habitacion: 'Pewmafe', fecha: { in: dates } },
    data: { disponible: false },
  });
  console.log(`  updateMany matched: ${result.count} rows`);

  // Restore
  await releaseDates('Pewmafe', new Date('2026-10-01'), new Date('2026-10-05'));

  await p.$disconnect();
}
main();
